image: python:3.7

tests:
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry config virtualenvs.create false
    - poetry install
  script:
    - pytest tests
